Fixed/implemented metanorma examples
plurimath/plurimath pull request #100
Opened 2022-12-22 16:24 UTC by suleman-uzair

Extracted examples from metanorma repos(metioned below) and added/updated Parslet rules for failing scenarios.

1. mn-samples-iec
2. mn-samples-itu
3. mn-samples-bipm
4. mn-samples-ieee-private
5. mn-samples-iho
6. mn-samples-iso
7. mn-samples-ogc
8. mn-samples-jcgm
9. mn-samples-nist

2022-12-26 08:39 UTC, HassanAkbar requested changes

2022-12-26 08:39 UTC, HassanAkbar commented on lib/plurimath/math/function/mod.rb
> +          second_value = wrapped(parameter_two) if parameter_two
The first line in the `wrapped` function is `return "" unless field`. Do we need an `if` condition here?

2022-12-26 08:39 UTC, HassanAkbar commented on lib/plurimath/math/function/unary_function.rb
> +            parameter_one&.map { |value| value&.to_latex }.join
```suggestion
            parameter_one&.compact&.map(&:to_latex)&.join
```

2022-12-26 08:39 UTC, HassanAkbar commented on lib/plurimath/utility.rb
> +        nodes&.each { |node| element << node unless node.nil? }
```suggestion
        nodes&.compact&.each { |node| element << node }
```

2022-12-26 13:08 UTC, suleman-uzair commented on lib/plurimath/utility.rb
> +        nodes&.each { |node| element << node unless node.nil? }
*`nodes`* variable contains **Ox::Element** object which supports *`each`* but doesn't support *`compact`*.

2022-12-28 03:47 UTC, ronaldtse requested changes

2022-12-28 03:47 UTC, ronaldtse commented on spec/plurimath/latex/metanorma_exampes_spec.rb
> +
The filename of this file contains a typo in `exampes`

2022-12-28 03:47 UTC, ronaldtse commented on spec/plurimath/latex/metanorma_exampes_spec.rb
> +RSpec.describe Plurimath::Latex::Parser do
@suleman-uzair for all imported specs/tests, can you label the source of the formula? e.g. `metanorma/mn-samples-iso:{path name}`?

2022-12-29 07:39 UTC, ronaldtse commented on spec/plurimath/latex/metanorma_exampes_spec.rb
> +RSpec.describe Plurimath::Latex::Parser do
Thanks, I've also updated it.

2022-12-29 07:40 UTC, ronaldtse commented
Thank you @suleman-uzair ! Could you help resolve the remaining comments from @HassanAkbar and then merge this?

2022-12-29 07:40 UTC, ronaldtse approved these changes

2022-12-29 13:29 UTC, merged