Fixed MathML conversion for dot class and increased code coverage
plurimath/plurimath pull request #156
Opened 2023-05-24 12:36 UTC by suleman-uzair

This pull request aims to
1. Enhance the **MathML** conversion process for the **dot** class, ensuring the accurate rendering of **dot** symbols in **MathML** format.
2. It focuses on increasing the code coverage.

closes #155

2023-05-26 05:28 UTC, ronaldtse commented
@suleman-uzair is this ready to go? Thanks!

2023-05-26 08:06 UTC, suleman-uzair commented
> @suleman-uzair is this ready to go? Thanks!

Yes, now it's ready.

2023-05-26 13:45 UTC, ronaldtse requested changes
Questions remain in the review comments

2023-05-26 13:45 UTC, ronaldtse commented on spec/plurimath/mathml/parser_spec.rb
> +            <mfenced open="(" close=")" separators="">
`mfenced` is a deprecated element that we shouldn't use?

2023-05-26 13:45 UTC, ronaldtse commented on spec/plurimath/mathml/parser_spec.rb
> +          <mathml:mstyle scriptminsize="6pt">
Why is the namespace called `mathml` here?

2023-05-26 13:45 UTC, ronaldtse commented on spec/plurimath/mathml/parser_spec.rb
> +            <mathml:mo rspace="-0.35em"/>
Why is this namespaced?

2023-05-26 13:45 UTC, ronaldtse commented on spec/plurimath/mathml/parser_spec.rb
> +              <mathml:mspace width="-0.15em"/>
Same here?

2023-05-26 13:45 UTC, ronaldtse commented on spec/plurimath/mathml/parser_spec.rb
> +              <mathml:mspace width="-0.1em"/>
Same here?

2023-05-26 14:56 UTC, suleman-uzair commented
@ronaldtse Yes, you're correct. Currently, we don't use the `mfenced` element for **MathML** conversion. However, during parsing, we still accept this element in user input. So, users can include the `mfenced` element in their input, but the output generated by **Plurimath** won't contain this element.
An example of this can be found in the **metanorma** repos available at: `mn-samples-bipm/site/documents/brochure-its90/brochure-its90-en.pdf.fo.debug.xml`.

2023-05-27 00:14 UTC, ronaldtse commented
I see, got it. Let’s merge this. Thanks!

2023-05-27 00:14 UTC, ronaldtse approved these changes

2023-05-27 00:14 UTC, merged