[WIP] Fixed binary classes symbol presentation flaws
plurimath/plurimath pull request #167
Opened 2023-07-07 15:46 UTC by suleman-uzair

This PR fixes summation symbols flaws in the presentation by upgrading 'sum', 'prod', and 'int' to ternary classes and updating OMML conversion methods.
This PR also updates.
1. Parser rules for all the currently supported markup languages.
2. Transformation rules for all the currently supported markup languages.
3. Rspecs of all the currently supported markup languages.

closes #165

2023-07-21 10:32 UTC, HassanAkbar requested changes

2023-07-21 10:32 UTC, HassanAkbar commented on lib/plurimath/math/function/ternary_function.rb
> +          end
This should be moved to respective classes.

2023-07-21 10:32 UTC, HassanAkbar commented on lib/plurimath/math/function/ternary_function.rb
> +          end
I think wherever we are using `if .is_a?(Classname)` type check can be moved to methods in the respective class. 
That way here we can simply do something like `field.underover_class?` here.

2023-07-26 07:55 UTC, ronaldtse approved these changes

2023-07-26 08:51 UTC, merged

2023-07-26 08:51 UTC, ronaldtse commented
Thank you @suleman-uzair , can you please help release soon?

2023-07-26 09:29 UTC, suleman-uzair commented
> Thank you @suleman-uzair , can you please help release soon?

Version 0.3.6 is released.