Updated parser rule and added spec for decimal values
plurimath/plurimath pull request #70
Opened 2022-10-17 12:11 UTC by suleman-uzair

Updated **AsciiMath** parser number rule, and constants and added specs for decimal values.

closes #69

2022-10-17 13:46 UTC, HassanAkbar approved these changes

2022-10-18 03:01 UTC, ronaldtse requested changes

2022-10-18 03:01 UTC, ronaldtse commented on spec/plurimath/asciimath/parser_spec.rb
> +          Plurimath::Math::Number.new("1"),
Actually, the original request is to parse these values all identically, i.e.:
* `0,1` == `0.1`
* `-.1` == `-0.1`
* `-0,1` == `-0.1`
* `-.1` == `-0.1`

Therefore the current expectations all need to be updated accordingly.

2022-10-18 10:31 UTC, ronaldtse commented
@suleman-uzair this PR should really only handle `0.1` (i.e. decimal point) not `0,1` the decimal comma.

The decimal comma requires further thought on what to use as number separators, I am not convinced that we have an immediate solution right now. Why don't we just skip this for now and deal with other urgent issues first?

Again, the "decimal comma" is NOT important.

2022-10-20 16:56 UTC, ronaldtse commented
@suleman-uzair is this to be merged?

2022-10-21 08:01 UTC, suleman-uzair commented
> @suleman-uzair is this to be merged?

@ronaldtse Yes, it's ready to merge.

2022-10-21 08:42 UTC, ronaldtse commented on spec/plurimath/asciimath/parser_spec.rb
> +          Plurimath::Math::Number.new("0.1"),
@suleman-uzair shouldn't this be:
```ruby
expected_value = Plurimath::Math::Formula.new([
  Plurimath::Math::Number.new("-0.1"),
])
```

2022-10-21 08:42 UTC, ronaldtse commented on spec/plurimath/asciimath/parser_spec.rb
> +        ])
Shouldn't this be:
```ruby
expected_value = Plurimath::Math::Formula.new([
  Plurimath::Math::Number.new("-0"),
  Plurimath::Math::Symbol.new(","),
  Plurimath::Math::Number.new("1"),
])
```

2022-10-21 09:46 UTC, suleman-uzair commented
@ronaldtse

2022-10-21 10:00 UTC, ronaldtse commented
@suleman-uzair  I’m not sure what the impact of that change is. Can you elaborate?

2022-10-21 11:14 UTC, suleman-uzair commented
> @suleman-uzair I’m not sure what the impact of that change is. Can you elaborate?

Changes in the parsing behavior of operators(- and +) in Asciimath won’t affect on output(but only in parser rules and spec values) because we are not making any changes to operators on output, but I have some questions regarding parsing rules,
should 1-2 be parsed as 1 and - and 2 OR 1 and -2 ?
should -a be parsed as -a ?
should a-beta be parsed as a and - and beta OR a and -beta ?

2022-10-22 05:05 UTC, ronaldtse commented
Thank you for the explanation @suleman-uzair ! I suppose the issue with `-` depends on whether it is a minus or unary minus operator. Parsing `-` as a an operator is indeed correct. Let's merge this. Thanks!

2022-10-22 05:05 UTC, merged