[WIP] Updated parser and transformation rules for new asciimath examples
plurimath/plurimath pull request #77
Opened 2022-10-18 17:35 UTC by suleman-uzair

Updated AsciiMath parser and transformation rules for new examples from **```asciidoctor/asciimath```**.

2022-10-22 05:10 UTC, ronaldtse commented
@suleman-uzair can we merge this or is this still a draft? Also could you help rebase to fix the conflicts?

2022-10-24 08:03 UTC, suleman-uzair commented
> @suleman-uzair can we merge this or is this still a draft? Also could you help rebase to fix the conflicts?

@ronaldtse This PR is yet in progress.

2022-10-31 13:53 UTC, ronaldtse requested changes

2022-10-31 13:53 UTC, ronaldtse commented on spec/plurimath/math/formula_spec.rb
> +        expect(formula).to eql('log1+2+3+4^"4 terms"')
This change doesn't seem correct.

The original:
```ruby
"log(1+2+3+4)^(\"4 terms\")"
```

And the converted back formula:
```ruby
'log1+2+3+4^"4 terms"'
```

Are rather different in element precedence.

2022-10-31 13:53 UTC, ronaldtse commented on spec/plurimath/math/formula_spec.rb
> +        expect(formula).to eql('oint1+2+3+4^"4 terms"')
Doesn't seem right. Should have been `oint(1+2+3+4)^"4 terms"`

2022-10-31 13:53 UTC, ronaldtse commented on spec/plurimath/math/formula_spec.rb
> +        expect(formula).to eql('underset(sumsin(theta))(i)')
Doesn't seem right. Should have been `underset(sum(sin(theta)))(i)`.

2022-11-02 00:20 UTC, ronaldtse approved these changes

2022-11-02 00:21 UTC, merged

2022-11-02 00:21 UTC, ronaldtse commented
Thank you @suleman-uzair !

2022-11-02 00:21 UTC, ronaldtse commented
> Updated AsciiMath parser and transformation rules for new examples from asciidoctor/asciimath.

@suleman-uzair can you help mark which specs come from asciimath so we can track them if they change in the future? Thanks!